### ISSUE TITLE
Add user permission to allow projects creation in Pootle

### ISSUE THREAD

**Issue by pyg77** [framasoft/pootle#1]
English
==========
Pootle only allows projects creation for admin.

What we want is a new user permission allowing users to "create a new translation project"

Requirements
  * add new user permission : create new project
  * as soon as a user has this permission, a "Create new project" link will be displayed next to his login name
  * this link will lead to a form (see https://lut.im/i3sRhsAw/4GG5Rl7w as an example)
  * when this form is submitted, the project is created, and permission "can administrate translation project" is given to the user, for this project. 
  * then the user is automatically sent to this project page, and optionnaly an email is sent to the user notifying him of the project creation, and giving him the link to the project page.
  * of course, all texts/interface elements must use Pootle i18n system

French
=============
Pootle ne donne la permission de créer des projets qu'aux administrateurs.

L'objectif est de créer un niveau de droits autorisant la création de projets.

  * dès lors qu'une personne possède ce niveau de droits, un lien « créer un projet » sera affiché en haut à droite de son login
  * ce lien conduira à une page proposant un formulaire pour créer un projet (voir ici https://lut.im/i3sRhsAw/4GG5Rl7w pour les champs nécessaires. Le formulaire peut évidemment se présenter de façon plus pratique/esthétique).
  * lorsque le formulaire est soumis, le projet est créé, en ajoutant automatiquement le droit "peut administrer un projet de traduction" à la personne qui a créé le projet, pour ce projet uniquement.   
  * ensuite la personne est idéalement redirigée vers la page du projet. Si cela n'est pas possible (compliqué, impossible ou toute autre raison), il faudra lui renvoyer un message confirmant la création du projet ainsi qu'un lien vers la page du projet.
  * bien évidemment, toute l'interface devra utiliser le système d'internationalisation de Pootle

**Comment by jnavila** [comment]
Bonjour,

Cette requête est-elle toujours d'actualité ? Pootle semble mort ou en voie, toujours en python 2.

**Comment by ldidry** [comment]
Non, plus vraiment en fait.

**Comment by pyg77** [comment]
Fermeture de l'issue (et du bounty) pour cause de migration à weblate

Bounty is closed.
